name: Boarding
favicon: null
layout_spectrum: 0.3894231882877648
typography_spectrum: 0.9728007731027901
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9656488529872149
  lightness: 0.3599104695022106
  saturation: 0.8874534014612436
  rhythmicContrast: 0.4956191193778068
purpose: []
